### ISSUE TITLE
Best practice for .seb routes

### ISSUE THREAD

**Issue by robertholf** [ndum/laravel-seb#2]
Thank you for this package, I am curious how you implement the .seb files. The examples provided `dd(` the encryptedSebConfig. Any recommendations on how to generate the .seb file? Any specific header (e.g. X-SafeExamBrowser-RequestHash) used?

**Comment by ndum** [comment]
Hi @robertholf 

Thanks for using this package! 

I primarily use it to store the SEB configuration as a blob in the database. However, it should also be possible to return the SEB config directly as a response or save it as a file.

```php
$encryptedSebConfig = SebConfigGenerator::createSebConfig($sebConfig, $startPassword, $quitPassword, $adminPassword);
$blob = new Blob(['encoded_config' => $encryptedSebConfig]);
$example->save($blob);
```

And later returns as laravel response:

```php
return response($example->encoded_config)
                ->header('Cache-Control', 'no-cache private')
                ->header('Content-Description', 'File Transfer')
                ->header('Content-Type', 'application/octet-stream')
                ->header('FileName', 'example.seb')
                ->header('Content-Disposition', 'attachment;')
                ->header('Content-Transfer-Encoding', 'binary');
```

i hope this helps!

**Comment by robertholf** [comment]
Thank you so much! Just curious what package you are using for `Blob`

**Comment by ndum** [comment]
Blob is just a laravel model, u just need binary as attribute in the database/migration:

```php
            $table->binary('encoded_config')->nullable();
```

**Comment by robertholf** [comment]
Thank you again!
